### ISSUE TITLE
Change "possibly broken" language

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1030]
Someone at a council recently contacted us because PlanningAlerts was saying their council was "possibly broken". This was because they'd genuinely not had applications for more than 14 days (which is a separate issue to this that we should probably look at too).

We discussed changing the language because it's a bit jargony (hackers call scrapers broken) and can make it sound like the council is broken, rather than the scraper (or more accurately that it just hasn't got any data recently).

I suggested changing it to "no recent data". The person at council suggested:

> Perhaps it may be better to word it as ‘no relevant applications’ as each organisation can choose what types of applications they wish to advertise in the planning alerts site.

**Comment by mlandauer** [comment]
It's definitely not the authority that is possibly broken! :-) Maybe we could say "scraper possibly broken" instead?

I think "no recent data" or similar is too weak a statement. It's possible that it's due to a council just not publishing anything for a couple of weeks but it's less likely than a scraper being broken.
