### ISSUE TITLE
Who are our donors?

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1050]
For the past couple of years we've sent out end-of-financial year emails to people signed up for PlanningAlerts asking for donations. Some of these people have generously donated to the OpenAustralia Foundation. We'd like to learn more about who they are and why it has been important to them to contribute to PlanningAlerts.

We did some research in 2015, as documented in these blog posts:

https://www.openaustraliafoundation.org.au/2015/01/16/getting-to-know-you/
https://www.openaustraliafoundation.org.au/2015/10/20/who-comments-in-planningalerts-and-how-could-it-work-better/

We'd now also like to answer the following questions:

- [x] How many alerts are they signed up for?
- [x] How many comments have they made?
- [x] Do they open or click email alerts?
- [x] How long were they signed up before they donated?
- [x] How often do they donate?
- [ ] How much do they donate?
- [ ] Where are they located and where are their alerts for?
- [ ] Have they emailed us?
- [ ] Do they use our other projects?

We’re answering these questions using a list of all our PlanningAlerts donors here https://docs.google.com/spreadsheets/d/1I-UYVbYewcbRQHfGVzuqLlISQShd0rgTS3Mps_taCCQ/edit#gid=100337463

**Comment by equivalentideas** [comment]
1. We've exported Contributors from CiviCRM who’s “contribution page” was either “PlanningAlerts donation” or “PlanningAlerts support donation”.
2. imported these into Google Spreadsheets
3. removed contributions with status “pending” or “refunded”.

**Comment by equivalentideas** [comment]
There are 507 unique emails for donors from **all time**. We’re taking this to mean there are this many people who've donated.

* 4 people had made 3 donations.
* 56 people had made 2 donations.
* 447 people had donated once.

**Comment by equivalentideas** [comment]
## How many alerts are they signed up for?

![screen shot 2016-11-23 at 3 26 04 pm](https://cloud.githubusercontent.com/assets/1239550/20551179/3bff5076-b191-11e6-9fc3-e080cdcaeaa9.png)

| Number of alerts           | Number of people  |
|-------------|-----|
| 0           | 79  |
| 1           | 302 |
| 2           | 82  |
| 3           | 23  |
| 4           | 8   |
| 5           | 5   |
| 6           | 4   |
| 7           | 2   |
| 8           | 2   |
| Grand Total | 507 |

**Comment by equivalentideas** [comment]
## How many comments have they made?

16% of these 507 donors have made at least one comment (using the same email as they donated with).

A rough calculation:

These 507 donors made 259 comment between them, or .51 comments per person.

Site wide, 40,519 people subscribers have made 8097 comments, or 0.19 comments per subscriber.

That's a rough comparison because not every donor is subscribed to alerts etc. but it's pretty stark. Even if you remove everyone who's commented more than 5 times from the donors, they still come out at 0.23 per person. This is not good statistics I know, but I think we can definitely say people who donate are much more likely to comment that general users.

Importantly, the vast majority haven't commented. There's also a strong sub-group who are commenting a lot.

| Comments made | Number of people | Percentage of total |
|---------------|------------------|---------------------|
| 0             | 426              | 84%                 |
| 1             | 40               | 7.9%                |
| 2 - 5         | 30               | 5.9%                |
| 6 or more     | 11               | 2.2%                |

**Comment by equivalentideas** [comment]
## How long were they signed up before they donated?

We don't know when 111 people signed up for PlanningAlerts because we only started recording a created_at date for alerts a while into the project. I've removed these people from these stats because I don't think we can say much about them. That's 20% of all donors.

There are 5 people who donated before signing up for an alert with the same email. These feel like an odd case that we can't draw anything from. I've filtered them out of these stats.

The average donor was signed up for 570 days (about 19 months) with the same email address before donating. This seems like a long time. More analysis needed, but I made a confusing chart and perplexed myself, so I'm going to leave this here for the weekend.

**Comment by equivalentideas** [comment]
## Do they open or click email alerts?

We can only check this at the moment by eyeballing the opened/click indicators on the emails send to each address in Cuttlefish. So rather than checking all 507, we're just going to sample 25 to see if there's any clear trend.

**What we see in these 25 reflects these people being very active PlanningAlerts users, opening almost all the emails they get and regularly clicking on applications**.

### Opening

80% of the 25 I checked opened all, or almost all, of their PlanningAlerts emails. Only 2 out the 25 opened less than half of the emails they got.

### Clicking

56% of the 25 clicked in some of the emails, about 20%. This is consistent with our general understanding that people only click on an Application in an email when it's one of interest to them.

36% clicked in above 50% of the emails they received. This seems high to me and my confirmation bias says this reflects these people being passionate users.

Only two people clicked in none of the emails they received.

**Comment by equivalentideas** [comment]
We've now answered the main questions were interested in for now. I'll close this and we can reopen with more questions etc. as we go.

**Comment by equivalentideas** [comment]
## Why did people who use PlanningAlerts donate?

We asked people why they donated in [a survey a couple of years ago](https://www.openaustraliafoundation.org.au/2015/01/16/getting-to-know-you/). When we filter the results down to people who are PlanningAlerts users, there's two main themes:

1. Because I support the values of open democracy PlanningAlerts embodies.
2. Because I use it and so feel a duty to support it when I can

Here's some extracts:

> “Because I believe in Open Australia and the ideals therein. In fact I would be happy to get involved further. ”
> 
> “I use PlanningAlerts service and I value it. I also highly regard OpenAustralia Foundation and the sense of transparency and freedom it brings into the society ”
> 
> “ i use it”
> 
> “It's a great, free service, that deserves my support”
> 
> “As I think you guys do a great job to keep things open and honest.”
> 
> “Because it provides a service I use !”
> 
> “I beleive in your open data/technology agenda whole heartedly. Democracy is a closed broken old boys club and needs to be re-designed and re-built.”
> 
> “I like what you do and work that opens up closed processes to scrutiny.”
> 
> “because I support its aims”
> 
> “Strongly support their goals to make information about how our government system works and what it's doing accessible.”
> 
> “To help you improve transparency on issues that could potentially affect me and my family”
> 
> “Rate importance of work very highly”
> 
> “"I donate because of the application noted above. A sensible non-political service that fills a niche that should more properly provided by local government.
> I am broadly of the opinion that we are poorly served by the interface between the 'big end' of town, transport and utility providers including government and the user public.  Any organization that seeks to redress the balance is welcome and worth supporting.”
> 
> “I use the services and feel it's a good service that make ppl in the area aware of what is happening especially housing development around them.”
