### ISSUE TITLE
find out what's important to people who donate to the project

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#1113]
Find out what's important to people who donate to PlanningAlerts by designing and carrying out new user research with people who have donated. This is a refresh on research done at #1050 two years ago. Update the brief at #1056 

> "These are things that we think are important for people who donate to the project:
> 
> By joining the crew you are making PlanningAlerts possible, which is an amazing thing. It let us send out 100,000 alert emails, like the ones you get, to people this week for example.
> All these other great people like you are supporting PlanningAlerts by joining the Crew.
> You feel appreciated by the OpenAustralia Foundation, who’s values you share.
> Henare, Luke, Kat, and the OpenAustralia Foundation team are speaking to you personally.
> "

**Comment by equivalentideas** [comment]
@kat @henare Is there anything specific we think has changed since [we collected these observations](https://github.com/openaustralia/planningalerts/issues/1050#issuecomment-263485118), that means we can't do this first milestone without fresh responses?

My feeling is that [the messages we pulled out of that as being important to communicate to these peeps](https://github.com/openaustralia/planningalerts/issues/1056#issue-191200771) rings pretty true with users and donors I've had contact with.

I agree its super important that we learn more from these people, and one of the reasons I'm excited about this project is that I think it'll put us in closer contact with passionate users.

Rather that doing this at the start of this milestone, could we get better insights in a lean way by rolling out this first milestone with https://github.com/openaustralia/planningalerts/issues/1060 ([Give people becoming a backer a chance to tell us why they think it's awesome](https://github.com/openaustralia/planningalerts/issues/1060))? That seems like a pretty good way to put us in direct contact with people and hear what's important to them. We could even follow up with people who provide interesting responses.
