### ISSUE TITLE
When people donate (via oaf.org.au) find out from them what they've achieved using the project, and/or why it's important to them

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1124]
When people donate to PlanningAlerts, find out from them why PlanningAlerts is important to the them and what they've achieved using it. Then we can learn about their motivations, and the impact that PlanningAlerts is having.

This is a versions of https://github.com/openaustralia/planningalerts/issues/1060 for our existing donations system ( oaf.org.au/donate / CiviCRM ) so we can start getting the feedback before [PlanningAlerts Backers](https://github.com/openaustralia/planningalerts/milestone/6) is deployed.

If we also send these messages through to our donations slack channel we can also use their frequency as quantitative information about how many people are donating. When we deploy PlanningAlerts Backers we’re looking to see this frequency increase.

**Comment by equivalentideas** [comment]
We think that the best time to get information from people is when they’re feeling really good because they just donated. This is based on my experience donating to archive.org and our general knowledge about how people behave.

We're going to add a form to the donation thank you / completed page for people who've donated via [the PlanningAlerts donations page](https://www.openaustraliafoundation.org.au/donate/planningalerts/).

We're looking into wordpress plugins for this.

**Comment by henare** [comment]
>If we also send these messages through to our donations slack channel we can also use their frequency as quantitative information about how many people are donating.

If we did this we'd only know the frequency of people that sent the message, not how many donate. We can already run reports in CiviCRM to find out how many people are donating.

**Comment by henare** [comment]
>This is a versions of #1060 for our existing donations system...

It's also worth pointing out that the source of inspiration for #1060 was PayPal. They (used to?) have a field called _Message_ on the donation form where you could enter a bit of free text. To our surprise we actually got a few people writing little notes, like this one:

![selection_002](https://cloud.githubusercontent.com/assets/48945/24177768/e19e49fa-0ef8-11e7-8842-a57a09000cb0.png)

If we want to follow that model then we need to change this a little bit:

>We think that the best time to get information from people is when they’re feeling really good because they just donated. This is based on my experience donating to archive.org and our general knowledge about how people behave.

It would actually be best to put a field in the existing form that people could fill out.

**Comment by equivalentideas** [comment]
> It's also worth pointing out that the source of inspiration for #1060 was PayPal. 

That's interesting! I've never seen that before :) For me the inspiration was the [survey and interviews](https://www.openaustraliafoundation.org.au/2015/01/16/getting-to-know-you/) we did where we heard donors stories of success with PlanningAlerts and go all those quotes about what's important to them.

> It would actually be best to put a field in the existing form that people could fill out.

Why do you think that @henare ?

**Comment by henare** [comment]
>>It would actually be best to put a field in the existing form that people could fill out.
>
>Why do you think that @henare ?

I already said that above @equivalentideas :point_up: if we want to follow the PayPal model of where this idea originally came from then we need to do that.

**Comment by equivalentideas** [comment]
> I already said that above @equivalentideas ☝️ if we want to follow the PayPal model of where this idea originally came from then we need to do that.

Sorry, I should have been clearer :) Why do you think following following PayPal’s approach is the best way for us to get the information we want with this issue?

Also:

>  I've never seen that before

:) That certainly wasn't what I was thinking about when we came up with that idea.

**Comment by henare** [comment]
Sorry, because I didn't explain thoroughly I think you're filling in some blanks.

I didn't say I thought following PayPal’s approach is the best way for us to get the information we want with this issue. [I said](https://github.com/openaustralia/planningalerts/issues/1124#issuecomment-288270072) if we want to follow the PayPal model, which is where this idea originally came from, then we need to put it into the form, not afterwards.

_Why do you have to do that if you want to copy that model?_

If you're trying to copy a model that you know works in a certain number of cases but then you change it you have introduced two variables. The fact you've copied it and the change you've made. This means that if it doesn't work then it's much harder to determine why - was it because you've copied the idea and didn't do it well or was the key factor the change you made? If you don't understand why then it makes it harder to make changes that could improve the outcome.

_Why would you want to copy the model described above?_

We know the PayPal model worked in some cases - that's what made us think of reusing it. We also know that asking people to message us similar feedback, albeit via email, on the thank you page does not work - we're pretty sure we've never got a message out of that. So that does give us a good reason to copy it but...

_What's this overly-long conversation all about, anyway?_

One element of the design. Like anything else we should review what other people have done and cherry-pick, but ultimately choose the best design for our specific case - that's where you come in! :smile: :man_artist: :man_scientist: 

>>I've never seen that before
>
>:) That certainly wasn't what I was thinking about when we came up with that idea.

You probably haven't seen that before but it's absolutely how we started talking about this idea. For realz, I promise :crossed_swords: :man: :heart:

**Comment by equivalentideas** [comment]
Here's the archive.org example we've been referring to

![screen shot 2017-03-22 at 2 40 51 pm](https://cloud.githubusercontent.com/assets/1239550/24181245/ee273dd4-0f0d-11e7-913b-508ce48be87d.png)
![screen shot 2017-03-22 at 2 41 01 pm](https://cloud.githubusercontent.com/assets/1239550/24181246/ee313ed8-0f0d-11e7-9f55-349575059071.png)

**Comment by equivalentideas** [comment]
We decided to go with the archive.org style of having a question on the end. Some variation on:

> We'd love to hear why you donated or anything else you want to tell us

**Comment by equivalentideas** [comment]
We're in the process of getting this to work using a [WordPress plugin cforms2](https://wordpress.org/plugins/cforms2/).

And a the slack Email integration to post people’s submission to our private slack channel that donations appear in "donations_box"

**Comment by equivalentideas** [comment]
We also want to make this form look like the donations form people have just been using which is pretty nice and clear styles with big buttons:

![screen shot 2017-03-22 at 4 37 43 pm](https://cloud.githubusercontent.com/assets/1239550/24183767/675ba748-0f1e-11e7-83ee-eba4bbf7dbac.png)

**Comment by equivalentideas** [comment]
Here's how we could get the form to look:

![screen shot 2017-03-22 at 5 13 49 pm](https://cloud.githubusercontent.com/assets/1239550/24184621/ff77f5aa-0f22-11e7-89c7-b1795b25c9ae.png)

**Comment by mlandauer** [comment]
People can add a message when they donate on oaf.org.au using donorbox
