### ISSUE TITLE
Limit the number of comments displayed on application#show

### ISSUE THREAD

**Issue by hisayohorie** [openaustralia/planningalerts#1136]
It is probably a better user experience if we use the same pagination logic we use in comment#index in application#show page. Currently, more user comments indicates more scrolling to get to the comment form at the bottom.

**Comment by mlandauer** [comment]
This is a tricky one. I agree that in some cases there are "too many comments" and it's a complete pain to go the comment form at the bottom. Pagination would be a sensible solution in that case. However, part of the motivation of putting the form at the bottom was that it was more likely to make people read other comments before posting their own. Adding pagination would reduce that again.

It's a hard one to know which is better. I'm going to suggest that since a large number of comments on an application is relatively rare that we just keep to what we're doing right now and keep things super simple.
