### ISSUE TITLE
Add the option of one-off donations back to donation page

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1172]
You used to be able to make a one-off donation to us but that's been removed on the current Backers page: https://www.planningalerts.org.au/donations/new

We've had plenty of people contact us asking about making a one-off donation and not being able to find out how to do that.

morph.io offers this option too: https://morph.io/supporters/new

**Comment by equivalentideas** [comment]
Great to capture this in a issue 👍 I think this needs careful consideration against the project aims before implementing and weighing up the pros and cons. E.g. is the pro helping people who might not otherwise donate worth the con of some people who might sign up for regular donations going for one-off instead?

> We've had plenty of people contact us asking about making a one-off donation and not being able to find out how to do that.

I do wonder if that's connected to the end of financial year donation drive. I'm interested to see if we keep getting those emails in a few months time.

**Comment by mlandauer** [comment]
We're now only doing donations from outside planningalerts
