### ISSUE TITLE
Administrators not notified of new councillor data contributions

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1217]
So they know contributions are awaiting their review and merge.

**Comment by hisayohorie** [comment]
^^ the reference is an accident. sorry!

**Comment by equivalentideas** [comment]
Over here https://github.com/openaustralia/planningalerts/pull/1241 @hisayohorie has presented a way to do this via email, so that admins get an email when there's a new contribution.

I was initially thinking that maybe an RSS feed would be cool instead, because we can plug that into Slack—but we can plug email into slack too :D so email is probably simpler in this case.
