### ISSUE TITLE
People contributing councillor details that prefer not to provide their contact details shouldn't need to click a link

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1229]
Currently if you don't wish to supply your contact information after submitting councillor data you click a link and then you're sent back to the home page with a message that says, "Thank you":

![selection_001](https://user-images.githubusercontent.com/48945/29442850-8ca7e962-8417-11e7-86f5-c5aefecf4efa.png)

![selection_002](https://user-images.githubusercontent.com/48945/29442861-9c7046aa-8417-11e7-8bcd-12d0db22886d.png)

Isn't the step of clicking the link just extra work for the user that they don't really need to do?

If there's no reason for it then I think we should remove it and just include in the page text that people don't need to fill this page in. We currently say, "This field is optional." but what we really mean is that this page is optional. We should say that and make people feel good about not submitting their personal data if they don't want to and that they've got nothing else to do :smile:

**Comment by hisayohorie** [comment]
@henare I think it goes back to the discussion we had here https://github.com/openaustralia/planningalerts/issues/1177#issuecomment-311240817

I think the larger message of the page is to say thank you to the contributor and let them know the impact they are making and what's the next step. So even if we move the optional contributor info form in the first page, I think it is still important to have this page. And if we would to have this page, the contributor has to click something to get to somewhere. 
But if you have ideas, I'm very curious to know if you have other suggestions on how we can thank them on spot other than having the page! 🚀

**Comment by henare** [comment]
>But if you have ideas, I'm very curious to know if you have other suggestions on how we can thank them on spot other than having the page! :rocket:

On our weekly status call today we had quite a few ideas. @equivalentideas is going to try and bring them together into some issues.

**Comment by equivalentideas** [comment]
So what we talked about in our call last week was the idea that this page is a bit confusing because it has a few purposes:

1. thanking the person for their contribution
2. telling them what will happen next with their data
3. explaining why they might like to provide their contact info
4. providing the mechanism for them to input information, or to indicate that they're not into that.

Because of the way people read a page like this, jumping up and down rather than from top to bottom, it makes the whole thing over-all more confusing. In testing this we saw that the person made their contribution, saw the big 'Thank you!', and said 'great that's done'. I then had to prompt them to re-look at the page and consider the second question about adding their contact info.

On our call, we talked about switching things around so the decision about adding your contact info comes before the final big thanks, and moving that question to its own page. The advantages here are:

* the person gets to consider sharing their information without other distractions, so this choice is easier to process and they wont miss this opportunity
* everyone gets a nice big thanks at the end
* the mental model of people contributing something is that they get thanked when they're finished. So having the thanks as the final step feels more intuitive.
* no new steps or clicks, just reorganised.

We imagined that this new page would just this question, with 'skip' or 'submit' buttons. This is a really familiar pattern that people will be used too, which is another advantage.

Implementation wise, this actually makes things simpler too. One way to do this on the contribution controller, is to insert a new action that the contribution gets passed to between #new and #create . The contribution id (or params if we optionally want to not save it until #create) can be passed through a hidden form element or something so they aren't ever exposed in params that [could be manipulated by a hacker](#https://github.com/openaustralia/planningalerts/issues/1228#issuecomment-325899443).

The #create action is still the final thank you page then—which is conventional. We can then completely remove the contributors controller.

The place to start with this is to amend the success integration test to include this step—if this is what we want to do :)

**Comment by equivalentideas** [comment]
Chatting with @hisayohorie we're still not completely clear on what we've decided, so I'm gonna have a go writing the test for this idea, and then @hisayohorie can implement it if it seems good.

**Comment by equivalentideas** [comment]
> Chatting with @hisayohorie we're still not completely clear on what we've decided, so I'm gonna have a go writing the test for this idea, and then @hisayohorie can implement it if it seems good.

Over on https://github.com/openaustralia/planningalerts/compare/move-contributor-details-question I've added tests for this flow, and made the old flow pending because we have to remember to remove all of that stuff (controller, views, etc.).

@hisayohorie would you like to implement this or assign it to me?
