### ISSUE TITLE
Remove councillor

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1271]
Samantha Ratnam is reported as no longer being a councillor -update councillor list for Moreland City Council - see Councillors still listed at https://www.planningalerts.org.au/applications/995438#add-comment

**Comment by kat** [comment]
Thanks for letting us know. I've reported this and hopefully we'll be able to update shortly. 

Do you have a URL where the current councillors for Moreland are listed?

Answering your question, we don't extract that kind of information, you might try asking the councils directly.

Warmly,


—
Kat Szuminska

--- original message ---
On Tue, Jun 5, 2018 at 03:57 pm, <notifications@github.com> katska wrote:


Samantha Ratnam is reported as no longer being a councillor -update councillor list for Moreland City Council - see Councillors still listed at https://www.planningalerts.org.au/applications/995438#add-comment

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by mlandauer** [comment]
We've hidden councillors everywhere because it's too much work to support currently. So, no need to fix this
