### ISSUE TITLE
Explain definition of "commercial usage" for API

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1350]
Currently we don't explicitly explain what we mean by "commercial usage" of the API. Some people have interpreted that to mean it's not commercial usage if the service that it's being used on is free. That is definitely not the case. If the organisation providing the service is a commercial organisation and the service is being offered as part of that organisation then it is commercial use. It doesn't matter if that particular service is free or not.

We should explain this in the API help text

**Comment by katska** [comment]
There's a bit to work out here @mlandauer 

One lens is structural - who is accessing the API - if on behalf of:
* A for profit organisation = commercial use
* Funded non-profit organisation = could be commercial or non-commercial
* Unfunded non-profit organisation or individual = could be either.

Some results from searching on defining commercial/non commercial use of data and APIs.

(reddit)
If your intended usage is commercial, you’ll need approval from us (either by filling out the API terms form or emailing api@reddit.com. **Use of the API is considered "commercial" if you are earning money from it, including, but not limited to in-app advertising, in-app purchases or you intend to learn from the data and repackage for sale. Open source use is generally considered non-commercial.**

Another potential way to put some of this:
**If you make money directly or indirectly, whether fee for service, grants, or you make money indirectly from the data insights**


A study in 2009 from Creative Commons, on what's understood by commercial use

Non-commercial according to wiki.creativecommons.org seems broad and vague.

Non commercial “primarily intended for or directed towards commercial advantage or private 
monetary compensation”

Whether NC-licensed content 
is appropriately used on websites or blogs supported by advertising is a question 
that CC is asked with some frequency. Some believe that because the web-
advertising model is based on traffic, any use of content that helps increase visits 
to a particular web page containing advertising is commercial. Others believe that 
the ad-supported model is an innocuous reality of web-based content distribution. 

Some also question whether use of content by a for-profit organization can ever 
be anything but commercial, while others believe that use by a not-for-profit 
should always be considered noncommercial regardless of the particular use. 

Further, some have questions about whether costs in connection with the use 
and further distribution of NC-licensed content may be recovered, and if so, how 
much (for example, may a school charge students for NC-licensed educational 
materials, and if so, may cost recovery include staff salaries?)
From
https://mirrors.creativecommons.org/defining-noncommercial/Defining_Noncommercial_fullreport.pdf

https://wiki.creativecommons.org/wiki/NonCommercial_interpretation#The_NonCommercial_license_element

**Comment by katska** [comment]
@mlandauer are there other examples that you think are relevant here, either for specific 
content, structure or approach?

**Comment by mlandauer** [comment]
> @mlandauer are there other examples that you think are relevant here, either for specific
> content, structure or approach?

Not that I can think of. Can you link to the document you have been working on which I think covers of most of what we need. It just needs refining and polishing.

**Comment by katska** [comment]
@matthew that doc is here 
https://docs.google.com/document/d/14mg_FpDR1l0U70QYJqwY-poh0VUH_N3H6AjeKhe5ocI/edit

**Comment by katska** [comment]
@mlandauer @jamezpolley a go specifically at the commercial use definition. Remember VOLUME use also needs to be added to this section too.

When do I need to pay to use planningAlerts?

You need to pay the OpenAustralia Foundation to use planningalerts.org.au, including signing up for alerts, and accessing the API in a business context, or you are making money directly or indirectly as a result of accessing this information.

This includes
Business, Non-profits and professionals, whether incorporated or not.
If you are part of an organisation using the service in the course of your business or operations, 
If you’re a person using the service in the course of your work.

This definition includes if you are a start up and have not yet made any money. Talk to us about cutting a deal with you. If you don’t know you have a product but you’re being paid or have points on something, we may be willing to help.

If you work at an academic institution, whether in research or teaching, you have funding, so we think its fair that you factor in a cost for accessing information of the sort you would pay for elsewhere.

**Comment by katska** [comment]
this is still highly relevant!

**Comment by katska** [comment]
I have shifted thinking on this and believe it would be more useful to say what a range of clear offerings are, rather than giving people definitions that will always be option to interpretation.

**Comment by katska** [comment]
@JoannaHill an issue I am very close to closing. Leaving open for now until our jam next week.

**Comment by katska** [comment]
changed framing to offers, so not needed now.
