### ISSUE TITLE
As a subscriber, receiving a large number of alerts all at once is surprising

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1376]
We've had feedback from  a subscriber who received an alert letting them know about "100 new planning applications". This seems to be because https://www.planningalerts.org.au/authorities/yarra_ranges was recently fixed, and so we scraped 7595 applications all at once.

If we don't have any way to avoid this, could we add one?

If we do have a way to avoid this, is it documented anywhere?

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ndt1)

**Comment by mlandauer** [comment]
There's no simple way to do this unfortunately. Because we can't depend on the date_received being always set for an application all we can do is look at the date_scraped and if anything new has appeared (using the date_scraped) since the last email alerts was sent to that person.

The best I suppose we could do is add some kind of heuristic to say "my, my there seem to be a lot of new applications... you probably don't want to see all of them."

The thing is it actually kind of already does that by only showing you a max of somewhere around 10 in an email alert and then just letting you know that there are a lot more with a link to follow.

So, I think I'll close this as a won't fix unfortunately.

**Comment by jamezpolley** [comment]
The same Yarra Ranges issue resulted in another email:

> I’m am emailing about an email as received. We have set up for the planning alerts and then we received an email which had our address listed as applying for a permit. We have not applied for any permits. 
> Can you please clarify why this has occurred ASAP. 

I've re-opened this so that I can link the email to this ticket.

**Comment by jamezpolley** [comment]
Reopening because we're continuing to get emails from people about this.
