### ISSUE TITLE
Provide guidance about impact/priority of fixing scrapers

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1399]
* https://www.planningalerts.org.au/authorities?order=population makes it fairly easy to find the broken scrapers with biggest population coverage
* There are other signals that might affect decisions on priority for which scrapers we want to look at first; for instance, the number of current alerts/subscribers in an area; how many times people in that area have contacted OA to ask for a scraper to be fixed, and how many donors we have in an area.

If we can surface this information, it might help make better decisions about the priority of fixing various scrapers.

**Comment by mlandauer** [comment]
We don't have any straightforward way currently to hook up any of those other signals to the authorities automatically. I agree they would be valuable. I have a feeling what is likely to happen is that, for instance, we will have many reasons (we already do) to add boundary information to authorities. It's a big task but we have many reasons, including some big user benefits, for doing this. Then, we would be able to easily find out how many alerts there are in a particular authority and we could add that to the list of authorities above so you could use that to assess the importance of fixing a particular authority.

So, I'm going to close this just because we're not likely to add this feature unless we come at it sideways.
