### ISSUE TITLE
Travis CI tests failing

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1403]
Discussion at https://travis-ci.community/t/cant-install-mysql-5-7-on-ubuntu-trusty/4311/5

The [suggested workaround](https://github.com/travis-ci/travis-ci/issues/9222) is to change the build to use Xenial instead of Trusty, but that doesn't work for us.

Travis have [asked MySQL](https://forums.mysql.com/read.php?11,677237,677237#msg-677237) to update repositories.

Mysql [have said ](https://forums.mysql.com/read.php?11,677237,677268#msg-677268)that they will no longer be providing any updates for Trusty as it is EOL.

**Comment by jamezpolley** [comment]
Using xenial for testing has [other issues](https://travis-ci.org/openaustralia/planningalerts/builds/562843828) and would deviate from the live environment, so I'm not going to pursue this.

**Comment by mlandauer** [comment]
@jamezpolley I'm happy to pick this one up if you want

**Comment by mlandauer** [comment]
Fixed in 15633d003f29bec0e8e67e13879dc617904da1fe. The switch to xenial was needed. Also xenial has become the default anyway on travis. Then, chrome headless wasn't supported (as far as I could tell) on xenial so switched to firefox headless which seems to be working. As usual a fair amount of tweaks were required to make everything happy. But it's working now!
