### ISSUE TITLE
Change requested attribution to refer to PA rather than OAF

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1414]
https://www.planningalerts.org.au/api/howto currently says:

> Low volume, non–commercial use of the API service is free. We ask that personal and non–profit use of this service attribute the OpenAustralia Foundation on your website or application.

We've realised that it would make more sense to ask for attribution to PlanningAlerts directly rather than the OAF in general. Where possible we'd also like a link rather than just text.

**Comment by mlandauer** [comment]
Yes, I agree. I think we should be more explicit about the wording and including a link.

**Comment by mlandauer** [comment]
This should also go on the page where a person requests a non commercial api key #1541

**Comment by mlandauer** [comment]
How about changing:
Low volume, non–commercial use of the API service is free. We ask that personal and non–profit use of this service attribute the OpenAustralia Foundation on your website or application.

To:
Low volume, non–commercial use of the API service is free provided an attribution to PlanningAlerts is included on your website or application. This should include wording to the effect "Development application data sourced from PlanningAlerts.org.au" including a link to https://www.planningalerts.org.au.

@katska I would very much appreciate your feedback on this wording

**Comment by katska** [comment]
@mlandauer How would you feel about requiring them to tell us where the attribution is and giving some specific examples of commercial or non-commercial. Having a go at something more specific. On the other hand I'm thinking some more general guidance would also be useful (I haven't done that here)

You may use the API service for free if 
* your usage is both non-commercial, and low-volume
* you provide an attribution to PlanningAlerts on your website or application,  the wording "Development application data sourced from PlanningAlerts.org.au" including a link to https://www.planningalerts.org.au.
* you contact <some appropriate email address here> with a link to the place of attribution, or otherwise evidence of that attribution for example if used in academic or other research.

If you are not certain whether your usage is considered commercial, please get in touch.

**Comment by mlandauer** [comment]
@katska this issue is to do with the attribution. It's confusing if a bunch of other issues are brought into this.

**Comment by mlandauer** [comment]
I think we should be asking for more information in #1541 which should allow us to easily check whether the attribution is being done. I feel like this might be a bit overkill for this first step.

**Comment by katska** [comment]
@mlandauer oh sorry I was looking at the last comment from you about wording and responding to that. I'll try and pay better attention to the actual issue in future
