### ISSUE TITLE
provide a context hint for addresses to help prevent wild errors

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1431]
**Is your feature request related to a problem? Please describe.**
Occasionally places with the same name or an incomplete address listed by a planning authority leads to an incorrect location shown in planningalerts. Google defaults to interpreting this address as in Brisbane, but its Melbourne.
for example 
https://www.planningalerts.org.au/applications/1449790

**Describe the solution you'd like**
The city council publishing this information is Melbourne, in Victoria, so it would make sense that the DA refers to Victoria, not Brisbane.

**Describe alternatives you've considered**
Ideally the planning authority would always give a complete address, but sometimes that doesn't happen. 
Being able to fix the locations by hand is another option, and maybe also useful in other circumstances. 

**Additional context**
It seems like we should be able to infer something of the location and stop wild errors like this one.
I'm interested to know if other wildly incorrect locations would be helped by associating addresses with geographical areas related to the council, and whether state level is sufficient?
How often does this happen? Add examples to this issue please.
This alert was sent to 620 people!

**Comment by mlandauer** [comment]
One solution (which I have a feeling is mentioned elsewhere) is to capture the full address coming out of the geocoder. I'm sure that the Google geocoder supports this feature. So for instance with the application above https://www.planningalerts.org.au/applications/1449790 the address "Southbank" is going into the geocoder. We currently only capture the latitude and longitude that comes out of the geocoder. We could also capture the full address that it's interpreting - in this case "South Bank, South Brisbane QLD". Then, we could show that to the user next to the address.

A second solution which is more complicated but I think ultimately better is for every planning authority to have a geographic boundary in the system and for the geocoder to use that boundary to force the result to be within the boundary or just say that the geocoding has failed because the result isn't where we expect it to be.

**Comment by katska** [comment]
@mlandauer yup the second solution sounds more sustainable in the long term! Is that a separate issue/project tho?

**Comment by mlandauer** [comment]
@katska thanks. Yes the second solution is a better one from the user point of view. It does require much more effort to implement but I do think it would be worth it. I've split it out into a separate issue #1529 and closing this one.
