### ISSUE TITLE
alerts says 12 results but shows 10

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1464]
someone received an alert that says there were 12 new planning applications but then only showed 10.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ygg5)

**Comment by mlandauer** [comment]
I think what's going on here is that there are 12 new applications for that user but we are intentionally limiting it to 10 in the email and then there's a link to see all the applications on the web

**Comment by mlandauer** [comment]
@katska actually I discovered a bug which is fixed in https://github.com/openaustralia/planningalerts/commit/051c6b0fe3ad39726e5bf67a76fdf625e706a72a. What was happening here is that only 10 were getting displayed and it was not showing a message about how to view the rest. That should be fixed now. It will show up to 15 in the email and if there are more it will tell you how to see them
