### ISSUE TITLE
make it easy to update an older DA from the admin panel

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1490]
PlanningAlerts site administrators would like to be able to instigate an update from admin panel when we know something has changed. 

A recent need came up when someone saw their name in a DA description. They had the council change the DA description but because it's an older DA there was no way to manually manually initiate an update from the latest information held by the public authority.

**Comment by mlandauer** [comment]
We currently leave it up to the scrapers to figure out which applications to look at. So, we can't implement what you've suggested without totally re-engineering the entire way the scraping process works. I would guess that this situation doesn't happen too often (maybe a couple of times a year?) so a simpler more manual approach might be fine.

@katska would an option where you can just edit the application in the admin panel be acceptable? We could make it so that there is a record of the change in the same way as when applications are scraped multiple times.

**Comment by kat** [comment]
yes!

—
Katherine Szuminska

--- original message ---
On August 23, 2021, 5:15 AM GMT+10 ***@***.*** wrote:



We currently leave it up to the scrapers to figure out which applications to look at. So, we can't implement what you've suggested without totally re-engineering the entire way the scraping process works. I would guess that this situation doesn't happen too often (maybe a couple of times a year?) so a simpler more manual approach might be fine.

@katska would an option where you can just edit the application in the admin panel be acceptable? We could make it so that there is a record of the change in the same way as when applications are scraped multiple times.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---

**Comment by mlandauer** [comment]
I did just reinstate the ability to completely delete an application. This is a nuclear option which is useful if the council has completely removed an application and we want to match the change because of privacy issues

**Comment by katska** [comment]
@mlandauer yes an option to update in the admin panel would be great. We'd need to be very clear it's only for that specific circumstance.  I seem to remember someone once telling me that FIDO had no/few controls so people couldn't ask to change things. This feels like one of those keep it narrow or open a vat of oil on a slippery slope.
