### ISSUE TITLE
collect comment failure stories to help understand how or why comment confirmation fails

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1515]
We get little flurries of comment failures sometimes. It can be hard to figure out the problem and requires a bit of back and forth to understand. Could the process of flagging an error be easier?
At the moment, as an admin, when someone has a problem confirming a comment the easiest thing to do is confirm it for them. Sometimes they just send an email saying "confirm" - Have they misunderstood, or not been able to confirm their comment? Again, it's quicker for me to just confirm the comment for them and move on. 

I asked the last person this happened to tell us what happened.

"I opened up confirmation email on mobile phone. From memory, I opened my comment (to see if all okay) but I could not edit comment so I went back into initial planning alert email and edited it there. Then  something happened (sorry, cannot remember steps) hence cut and paste job. Some admin comments were obviously dragged across but in the end, all good."

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3l8jp)

**Comment by mlandauer** [comment]
Is it possible that this confusion would be reduced by moving over to a user registration based system instead?

**Comment by mlandauer** [comment]
My intuition is that there is something fundamentally confusing to people that we are just simply missing and not understanding

**Comment by kat** [comment]
In some cases they have trouble following the link. And if there's user registration, that'll solve some problems. I think too that we'll start to see new ones ;)

—
Katherine Szuminska

--- original message ---
On August 23, 2021, 6:01 PM GMT+10 ***@***.*** wrote:



My intuition is that there is something fundamentally confusing to people that we are just simply missing and not understanding

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---

**Comment by katska** [comment]
I'll collect stories :) Sorry, I didn't see the title when in Front because
it clips very quickly into the subject line displayed. So it's a rubbish
way to review those emails!

**Comment by mlandauer** [comment]
@katska since you've put your hand up to do this, I'm assigning this to you. :-)
