### ISSUE TITLE
add physical address to confirm your alert text

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1519]
In this text

Now check your email

Shortly you should receive an email from PlanningAlerts.org.au. Click on the link in the email to confirm receiving planning alerts **for <insert address here>**

Text in bold is the new suggested bit.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3p1fp)

**Comment by mlandauer** [comment]
@katska I don't understand the rational for adding this. From a quick scan of the email in front it looked to me like there was a problem with the address that the person put in when they signed up for the alert. I don't understand the connection

**Comment by mlandauer** [comment]
I'm going to close this because it's unclear

**Comment by kat** [comment]
The issue was to help make clear the address that they're confirming an alert for. Yes the problem may have been earlier, but they didn't notice it then. Here's a 'make this address stand out more, so it's obvious to the person who signed up what the address is'. 


It may not be the right way to do that? Got a better suggestion @matthewlandauer

—
Katherine Szuminska

--- original message ---
On August 29, 2021, 7:14 PM GMT+10 ***@***.*** wrote:



Closed #1519.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---

**Comment by mlandauer** [comment]
The confirmation email includes the address already and changing one word "for" I don't think is going to make any difference to the visibility of the address.
