### ISSUE TITLE
shellharbour's old development applications not showing 'oops, too late' mesage

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1546]
Looking at a couple of applications for  (at random) that have been determined I see that the 'oops your too late' message isn't coming up, so the DA still looks open for comment. 
I'm guessing we're not reading the 'closed' date and they're staying open for ever as a result. 

For example 
https://www.planningalerts.org.au/applications/1696227
https://www.planningalerts.org.au/applications/1883923
https://www.planningalerts.org.au/applications/2002928

**Comment by mlandauer** [comment]
@katska have you looked if that "close data" information is available on their site?

**Comment by kat** [comment]
That depends on what's considered to close it. There's an 'approved' status. That should render the matter closed I'd say. Are there only specific clues we use to show whether closed for comment?
Its the council who have let someone know that their comment wont be considered because from an external website and outside the timeframe.
My thinking is that if all their DAs never look closed then a bunch of comments are made unaware that they're not going to be considered as part of that particular DA review and that could get tedious pretty quickly for the council.

—
Katherine Szuminska

--- original message ---
On September 13, 2021, 12:10 PM GMT+10 ***@***.*** wrote:



@katska have you looked if that "close data" information is available on their site?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---
