### ISSUE TITLE
Password management enablement

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1640]
When activating a user account, fields don't accept being filled by password manager.  This was found when trying to use LastPass.

**Comment by mlandauer** [comment]
When you're activating an account you're choosing a new password. So, I wouldn't expect Lastpass to try to fill out the password because you haven't set one yet. However if everything is working as expected I would hope that LastPass prompts you to save the password that you've chosen. Is that what happened @JoannaHill?

I'll close the issue on the assumption that that was the issue. If it wasn't please reopen it.
