### ISSUE TITLE
Set rules for responsive elements

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1661]

**Comment by JoannaHill** [comment]
- [ ] landing page search box
- [ ] Headline
- [ ] illustration

**Comment by mlandauer** [comment]
I've done a little investigation on screen sizes that we should support. I went into google analytics and looked at the analytics for all users on the site between 17 March 2022 and 17 March 2023 (the last 12 months). I exported the data into google sheets, split the screen sizes into seperate rows for width and height. Then, after sorting all the data by width I could create a cumulative total percentage of users who have less than a given screen width.

0.0025% of users have a screen width less than 320 pixels.
Roughly 3% of users have a screen width of 320 pixels.

That makes it pretty clear to me that we should support 320 pixels as the smallest width as a significant number of people see the site at that size but there are very few who see it smaller than that. This also matches up with what other people recommend. See for instance https://uxpickle.com/what-is-the-smallest-screen-size-you-should-design-for/

The single most common screen size is 1920x1080. Roughly 12% of all users see the site at that size.

96.4% of users have a screen width of 1920 or less. So there are still a significant number of people who look at the site on a larger screen. No surprises there.

3440 looks like the biggest reasonable screen width that we should think about because 99.8% of users have that width or less.

**Comment by mlandauer** [comment]
Looking at what would be a 95% or 99% confidence interval:

96.1% of users have a screen width between 321 and 2560 (inclusive)
99.4% of users have a screen width between 320 and 3432 (inclusive)

**Comment by JoannaHill** [comment]
Hamburger navigation investigations:

[James Foster of Exisweb](http://exisweb.net/menu-eats-hamburger) ran a few very interesting A/B tests to see if simply tweaking the hamburger menu icon would significantly increase usability and reduce confusion. He found that icons labeled with the word “Menu” significantly increased the amount of clicks as compared to a normal hamburger menu, by as much as 20%.

If you’re not looking to make a big change to your app, but want to increase usability, this would be a good alternative. The Nielsen Norman group also recommend labeling the hamburger menu for increased conversions.

**Comment by JoannaHill** [comment]
Looking back at what we wanted to achieve here, we think we've completed this issue. All the responsive rules have been set for the all components of this page to the fidelity necessary to test scale and proportion. All other design and responsive rules can be set in future milestones. 

We've also reviewed the central content colum and decided on 1280 (inclusive of z x 40px margins)
