### ISSUE TITLE
Auto-reply to alert email

### ISSUE THREAD

**Issue by sabpop** [openaustralia/planningalerts#1688]
**What is it?**
An auto-reply email that is sent automatically when users reply to an alert. It links them to the [Contact us](https://github.com/openaustralia/planningalerts/issues/1684) page. It also explains why Planning Alerts is switching to auto-reply to alerts. 

**What we heard?**
Through research we found that:

- There are countless blank and auto-reply emails to alerts clogging up the Planning Alerts inbox. 
- They require manual sorting and archiving, sometimes support staff reply to blank emails with canned response to understand if the person really needed help or if it was an accident. 
- There is a high number of people replying to alerts with the intention of making a comment
- There is a high number of people replying to alerts thinking they are speaking with council, asking for extra information on an application
- There is a number of people responding to alerts when they observe that there's something wrong with the alert eg. wrong address or picture
- Support staff are spending time investigating what's going on for each particular user

**Read more in the User Experience Map on Miro here:**
https://miro.com/app/board/uXjVPrTUbvg=/

Focus on cards in the map titled: Replying to an alert, When an alert is missed or late, Contacting PA thinking it's council, Amending a comment, There's a problem.

**Hypothesis**
An Auto-reply email would: 

- Reduce the amount of people emailing in by mistake
- Reduce the amount of people emailing in about known issues
- Eliminate the manual work required to sort through auto-reply and blank emails
- Reduce the work required to figure out why users are emailing and how to help them

**Design specifications**

- Editing and refining of copy on this page will be required
- Provide a link to the Contact us page so people who actually need to can get in touch
- Explain why Planning Alerts is shifting to auto-reply
- Consider adding links for common queries eg. Writing a comment or contacting council
- Will need a visual design/ information hierarchy look over as per: https://github.com/openaustralia/planningalerts/issues/1708#issuecomment-1524704877

**Sketch/ wireframe**
<img width="1261" alt="Screenshot 2023-04-04 at 10 58 48 am" src="https://user-images.githubusercontent.com/127382981/229666779-aec3fc3c-64cf-45aa-a611-ae60bf72ddfd.png">

**Comment by mlandauer** [comment]
There's a first pass of the auto-reply working in production now. When you email no-reply@planningalerts.org.au you get back an email like this:

![image](https://user-images.githubusercontent.com/2221/235401297-556dc1e0-052c-4715-84bb-f09fa1ad72b5.png)

Some small, not entirely obvious decisions I made along the way:
* Decided on using "no-reply" instead of "do-not-reply" for the email address to be a tiny bit friendlier
* Used an open source transactional email template from postmark: https://github.com/ActiveCampaign/postmark-templates/blob/main/templates/basic-full/example/content.html
* Did some small tweaks on the wording - split long sentences mostly.

Something that niggles me is that the email address in the first paragraph gets automatically linked on gmail and elsewhere too I think. This makes the "contact us" link much less obvious. So, I think we should do something to address that.

**Comment by mlandauer** [comment]
I've also changed "Oops!" to "Oooops!" like in the original text above to be a little sillier which I think is good here. I hadn't noticed it at first.
