### ISSUE TITLE
Add a -/+ for Disclosure text 

### ISSUE THREAD

**Issue by sabpop** [openaustralia/planningalerts#1710]
**What is it?**
In instances where we have a bit of text that drops down. Add a + or - or an arrow to show that the text can be expanded and minimised. 

**Why?**
Without the little indicator it's not obvious to users that the text can drop down and be minimised. 

**Screen shots:**
![Screenshot 2023-05-02 at 3 55 03 pm](https://user-images.githubusercontent.com/127382981/235590433-0bb991c2-3a34-4e5d-b373-98de0962e57f.png)
![Screenshot 2023-05-02 at 3 54 54 pm](https://user-images.githubusercontent.com/127382981/235590440-64cbe9c1-b3c2-41c5-a75f-75131e38994e.png)

**Comment by mlandauer** [comment]
Thinking it would be good to use the html5 details and summary tags for the disclosures. After thinking some of the design details and fiddling with the monstrous css that's currently running the site I figure we might as well just wait to implement this as part of the redesign we're working on instead. I'll assign this to @JoannaHill to include in her design

**Comment by JoannaHill** [comment]
![Screen Shot 2023-05-22 at 10 15 49 am](https://github.com/openaustralia/planningalerts/assets/17328152/f550a14c-b99c-4474-896f-d81a30bce64d)

Have explored adding a little arrow that can point up and down to indicate expand/contract functionality. Have also created a new flow for some of this content because it felt like we are trying to communicate a lot at once. New flow attempts to step out information more. Shall share more at design review this Wednesday.
