### ISSUE TITLE
Under the hood page status shows outdated scraper output log and is misleading

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1724]
This is a bit tedious as it gives the wrong first impression of what's happening in the status overview. I also have to remember it's wrong giving an extra layer of stuff to remember in the already tricky world of tracking down scraper problems. 
Could be part of a 'make it easier to stay on top of scrapers' project. 

Here's an example 

https://www.planningalerts.org.au/authorities/byron/under_the_hood
the latest scraper output from morph is shown as 
```

Most recent import logs

0 applications found for Byron Shire Council, NSW with date from 2023-08-09 
Took 1 s to import applications from Byron Shire Council, NSW
```

But the most[ recent log output for Byron in the masterview scraper](https://morph.io/planningalerts-scrapers/multiple_masterview) reads

 ```

 Collecting feed data for byron...
 byron: ERROR: 403 => Net::HTTPForbidden for https://datracker.byron.nsw.gov.au/MasterViewUI-External/ -- unhandled response
 /app/vendor/bundle/ruby/2.5.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:329:in `fetch'

```

**Comment by mlandauer** [comment]
Those two logs are showing different things. The first one on PlanningAlerts is showing what happens when the morph.io data is imported into planningalerts. So, it will show things like PA having difficulty contacting morph.io or some of the data not validating, etc.. The morph.io log on the other hand is showing the output of the actual scraping. So, yeah two different things.
