### ISSUE TITLE
Enhancing User Contact: Mandatory Email or Account Sign-In for Contact Us Form

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1741]
The  'Contact Us' form has been terrific improvement to help focus people's questions and minimise spam. And we've now no empty emails appearing in the inbox. However - There's an issue emerging  where a subset of users submit queries expecting a response, but fail to provide an email address. This leads to an inability on our part to respond, likely causing frustration for these users who are expecting a reply.

Problem:
When users fill out the 'Contact Us' form, they sometimes omit their email address. This omission seems unintentional, as these users appear to be expecting a reply based on the nature of their queries. This situation not only prevents effective communication but also potentially damages user experience and trust in our service, the latter being something high on our priority list in the redesign.

Proposed Solution:
To address this, I propose making the field for an email address in the 'Contact Us' form mandatory unless they're signed in. This change would ensure that every query received through the form can be addressed appropriately.
If they don't need an answer and it more feedback than question email could be optional but that's maybe overcomplicating it?

Benefits:
Ensures effective communication with users seeking assistance or information.
Improves user experience by reducing the instances of unaddressed queries.
Enhances the reliability and user trust in our support system.

Implementation Considerations:
Update the form to include a mandatory email field unless the user is signed in.
Provide clear instructions on the form indicating the necessity of an email address for a response.
Ensure the user interface remains user-friendly and intuitive with these changes.

**Comment by katska** [comment]
one of those who wrote to us was from council even!

**Comment by mlandauer** [comment]
I've looked through the code and run some tests and it looks like email is already a mandatory field if you're not logged in. It looks like it's been there since at least april of 2023 which I guess when it was first implemented.

Note that it doesn't check that the email address is valid because that's just too fraught to do in practise for all sorts of weird reasons. Instead it just makes sure that the field is filled with _something_.

If you're convinced that this is still a problem please reopen this and include some links to some examples where people are getting in touch without an email.
