### ISSUE TITLE
Text improvement for the button going to council website "More about this DA at NSW ..."

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1791]
From Kat from bugherd: When I came to this page fresh and see 'view more at NSW ...." I read that as I'll be taken to the NSW ... website and see more DAs rather than read more information about this DA. "information" is a long word but adds clarity. If information isn't wanted and info is not preferred (and I don't love that either) 

So how about something like: **"More about this DA at NSW ..."**

[https://www.bugherd.com/projects/366470/tasks/66](https://www.bugherd.com/projects/366470/tasks/66)

**Comment by JoannaHill** [comment]
I think this is much clearer that what we currently have. Especially after some very informal testing with friends. 
Here is how that would look (Figma mock up): https://www.figma.com/design/GEaOuajueHGvfaFPsOUZ9n?node-id=4226-314#909095169

**Comment by JoannaHill** [comment]
Feedback from one user is interesting to consider in this issue:

August 2024
_Greetings Planning Alerts,

I would like to suggest that you include the link "More Info", that appears on your website when one clicks the underlined address of the application in the email, in the body of the alert email. Or, at least explain that that's where the link is to the actual application in the body of the email.
In my view, it's not clear where one can get to the application from either the email or the website. Thanx. :hugging_face:_

**Comment by katska** [comment]
@JoannaHill this seems like an interesting and not entirely straightforward request! My thoughts and questions as follows
- yes would love to see an option to go straight to more information at council or other planning authority in principle, and not be a gatekeeper.
- it's not always straightforward to view more information, for example when there aren't persistent links at the planning authority page, or if the DA is not yet at the 'on notice' stage, an experience we improve through website now. 🌹 
- if they go straight to planning authority from the email alert they also lose the ease of commenting straight from Planning Alerts DA page. Perhaps there's another way?
- we do want people to easily find a way to be well informed before commenting, which seems easier if they've followed a link in the browser so both pages are in one app, rather than switching from email to browser and back
what's your take?

**Comment by JoannaHill** [comment]
Your thoughts are the same as mine. 
Matthew also agrees we can't send people to Council sites just because they're so often broken links. 

I do however want to change the wording on the button on the website which you suggested here and I think would help with clarity. 

I think there's a bigger woolier issue about the mental model of a users understanding of what Planning Alerts offers. Which I'm guessing wasn't clear for this user. That could be something to dive into given some time.

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/85a5396f-aca9-4366-b8e3-097807fdc68a

**Comment by JoannaHill** [comment]
Matthew and Jo have reviewed this today and in fact see an opportunity to re-model the entire way we refer to the source content. Jo will do some design ideas.

**Comment by JoannaHill** [comment]
Ok, following on from some design experiments we'd landed on the best next step is for some live A/B testing.

**What we would hope to learn is** 
How prominent does the button need to be for people to easily access it? 

**What we would test is**
A - the existing site which uses a large green button that should now be labelled 'View application source" and is very prominent
B - [New design](https://www.figma.com/design/GEaOuajueHGvfaFPsOUZ9n?node-id=5025-826#935707919) that simply hyperlinks with 'View source' nested in the 'Date Sourced' area

![Image](https://github.com/user-attachments/assets/9d333de3-8a11-4e54-a5a2-75412390949f)





![Image](https://github.com/user-attachments/assets/c06f3e3a-a8d4-4ab4-a45d-baa70795e200)

**Comment by mlandauer** [comment]
Tiny thing @JoannaHill should the alternate design with just the link next to the Planning Authority name have the external link icon? My feeling is it should because it's useful to get the visual reinforcement that this is taking you elsewhere.

**Comment by mlandauer** [comment]
I'm going to do the first step which is to change the words on the button

**Comment by mlandauer** [comment]
Text has been changed in https://github.com/openaustralia/planningalerts/commit/4b07f628f075a9bf66bfe7335037d47a29417309
