### ISSUE TITLE
Number of people notified is missing

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1871]
On [this DA page](https://www.planningalerts.org.au/applications/1061562) the number of people notified is missing in the "Notified" section (see screenshot)

![People were notified](https://github.com/user-attachments/assets/253894de-34a6-4b49-a446-12f34f0e486b)

**Comment by katska** [comment]
I tried a few DA numbers at random, and it's a consistent error. This is all requests & not an occasional anomaly.

**Comment by mlandauer** [comment]
What's going on there is that it's not showing the number currently if "0 people were notified" - that could be because the applications is very old before we recorded this number or the application is so new that people haven't yet been sent email alerts about it. In the old planningalerts we would just not show the information if the number was zero. Or we could obviously say "0 people were notified ...". I'd probably go towards the just not showing it. @JoannaHill what do you think we should do here?

**Comment by JoannaHill** [comment]
100% do not show that row. Please and thank you.
