### ISSUE TITLE
Add number of people with multiple alerts to admin interface

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#617]

**Comment by equivalentideas** [comment]
This sounds like it's related to the subscribers idea to me, base on the time it was made. We have since added the total number 'potential subscribers' (people with 3 or more alerts who don't have a subscription) to the 'subscribers' admin page.

That's pretty close to this number and gives us a rough idea of how many people have 3 or more alerts set up so I'm closing this. If there that doesn't serve the problem that this issue aims to solve, please reopen and explain :+1:
