### ISSUE TITLE
Add something to the alerts of subscribers

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#713]
A thank you and something about how to unsubscribe?

**Comment by equivalentideas** [comment]
I'm thinking the same as the confirmation page:

> You’re a paid subscriber so feel free to to sign up for alerts from as many locations as you need.
> You can cancel your subscription at any time, just email us.

I wonder if you can put an emoji gold star in an html email? ;) :star2:

**Comment by equivalentideas** [comment]
I was thinking this should go in the footer as these people want to get on with their alerts—but I just noticed it would be going right next to where it says 'PlanningAlerts is a free service run by ...' and all the donation stuff.

I think we can sub out these two lines for the subscription stuff:

> Find PlanningAlerts useful? Support this charity-run project with a tax deductible donation.
> PlanningAlerts is a free service run by the independent charity OpenAustralia Foundation. Discover our other projects.

Because these people are already 'supporting this charity-run project', and they aren't likely to be particularly interested in our other projects—and it's not free for them.

**Comment by henare** [comment]
Good call.
