### ISSUE TITLE
[PlanningAlerts/production] ActionView::Template::Error: undefined method `*' for nil:NilClass

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#757]
## Backtrace

    line 3 of [PROJECT_ROOT]/app/helpers/subscriptions_helper.rb: price_in_cents
    line 8 of [PROJECT_ROOT]/app/views/subscriptions/_stripe_button.html.haml: _app_views_subscriptions__stripe_button_html_haml__704864749_117819960
    line 19 of [PROJECT_ROOT]/app/views/subscriptions/new.html.haml: block in _app_views_subscriptions_new_html_haml__741711689_117690870

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/14828696)

**Comment by equivalentideas** [comment]
When [`#price`](https://github.com/openaustralia/planningalerts/blob/master/app/models/subscription.rb#L40) was called on my subscription as part of the [price_in_cents helper](https://github.com/openaustralia/planningalerts/blob/5d136f69d7e0db820e5f3ec3886edaaa775e3020/app/helpers/subscriptions_helper.rb#L3) it returned nil because I don't have a plan id. It raised:

    ActionView::Template::Error: undefined method `*' for nil:NilClass

This looks like expected behaviour @henare , as [subscriptions get a plan ids when they're created now](https://github.com/openaustralia/planningalerts/blob/master/app/controllers/subscriptions_controller.rb#L16), so it's raising an error because there's some problem there.

However, there's no specific mention in the commit message when this behaviour was changed in https://github.com/openaustralia/planningalerts/commit/25ebb64427f32e915e325eaa7b49c045351f0c08 so I made this issue to check with you :)

**Comment by henare** [comment]
@equivalentideas thanks for raising this. It's because we now require a `stripe_plan_id` value and our subscriptions in production didn't have this. I should have included this in a migration but as there's only our test ones created (and I've updated these in production) this is safe to close.
