### ISSUE TITLE
API: Current vs Historical Data?

### ISSUE THREAD

**Issue by PGScully** [openaustralia/planningalerts#796]
How do I tell if an application from your API is current (e.g. open for comment)?  Ideally I use your on_notice_to field, but this is frequently null.  When this happens I'm defaulting to date_scraped + 6 weeks.  Is there a better way?

**Comment by henare** [comment]
Thanks for opening this @PGScully.

>Ideally I use your on_notice_to field, but this is frequently null.

Unfortunately this is most commonly the result of not having the data available from the council.

>When this happens I'm defaulting to date_scraped + 6 weeks. Is there a better way?

In PlanningAlerts we never close comments and we don't try to do something like that (because it'd often be wrong). Here's what an application looks like if we don't have the data: https://www.planningalerts.org.au/applications/574317

Because this is a problem with the source data, and not something we'll be able to fix ourselves I'll close this issue.
