### ISSUE TITLE
As someone interested in a local development, show me the most recent comments on an application first, so I get the most recent information from people and see that other locals have commented recently

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#798]
At the moment, if you land on a DA with a number of comments, you see that oldest comment first. The older the DA, the more this gives the impressions that comments are infrequent—I think “huh, no one has commented in 2 weeks”:

![screen shot 2015-10-07 at 12 04 55 pm](https://cloud.githubusercontent.com/assets/1239550/10326903/79696bd0-6cec-11e5-9974-967ba5cccc87.png)

Then you go all the way to the bottom and see, actually another local has commented 5 minutes ago. The sense that people are acting around you now encourages you to take action.

The order of the comments is now much more noticeable now that the time is a more prominent part of the comment item (moved in #792).

Sometimes there are more recent comments that provide helpful, more up-to-date information about the application as well. For example, a comment explaining that an application has been withdrawn. These are easy to miss when they are way down the page.

I think we should reverse the comment order on the application page to show more recent comments first.

**Comment by henare** [comment]
>I think we should reverse the comment order on the application page to show more recent comments first.

As per https://github.com/openaustralia/planningalerts/pull/800#issuecomment-146403706, this does not take into account important ramifications of making this change. Because we've discussed these ramifications before and they're not included in this issue I'm closing it as incomplete.

Please reopen a new issue that either only reports the specific problem or, if it proposes a solution, includes complete details about the design ramifications of making this change and their mitigation. Specifically how is the conceptual confusion, of adding your comment to the bottom of the comment list but having it appear that the top, addressed?

---

Some other observations about design priorities:

>At the moment, if you land on a DA with a number of comments...

It's worth noting that this is a rare occurrence - the vast majority of DAs have no comments or very few comments.

>...The older the DA, the more this gives the impressions that comments are infrequent—I think “huh, no one has commented in 2 weeks”:

If no one has commented for 2 weeks then there's a good chance the commenting period is over. We don't want to design for a situation that we don't want to encourage, i.e. people commenting on expired DAs meaning their comment is more likely to be ignored.

>Sometimes there are more recent comments that provide helpful, more up-to-date information about the application as well. For example, a comment explaining that an application has been withdrawn. These are easy to miss when they are way down the page.

This is an exceedingly rare situation and one that our commenting system is not designed around. Changing the layout to suit a situation that almost never happens and one that we've not given much design thought to does not seem like a good idea to me.
