### ISSUE TITLE
Alert people in the area when a councillor replies

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#847]
Extracted from #812. See also #811.

**Comment by equivalentideas** [comment]
I think a simple way to do this for people is to initially just include replies like current comments. They’re not going to really stand out like this, but it keeps the alert email simple, consistent and familiar for people:

![screen shot 2015-11-10 at 11 44 46 am](https://cloud.githubusercontent.com/assets/1239550/11051112/7e3bd76e-87a0-11e5-8fd0-6db6251d506b.png)

**Comment by henare** [comment]
:+1:

**Comment by equivalentideas** [comment]
Closed by https://github.com/openaustralia/planningalerts/commit/378f9e086650ec481c21e4765bb6f6939312cb03

**Comment by equivalentideas** [comment]
Reopening this to do the text version

**Comment by equivalentideas** [comment]
The text version is added, and the replies moved out of the comments section of the email, into their own section in:

da098ec Make replies section header text consistent with other sections
1d94eae The important thing here is who is replying, so emphasise that too
e8acc5a Remove unused instance variable (refactor only)
94e38fb Separate comments and replies in text version of alert email
4a43b51 Make the intro text for the replies section of html email alerts nicer
a0b0cbc Require replies so that all the items are the same
5521dbe Refactor by using to_sentence method instead of building it ourselves (refactor only)
6d38a74 Extract variables
77663bb Reorganise logic for readability (refactor only)
22e7303 Separate replies from comments in alert email subject
0e1e06d Improve diffs in tests
69a9453 Separate replies and comments sections in html alert
77d33a7 Add replies from councillors to text version of alert emails
