### ISSUE TITLE
Decide what councils to launch our MVP with

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#853]

**Comment by henare** [comment]
I think it would be good for you to think about this @equivalentideas so I'm going to assign it to you.

**Comment by equivalentideas** [comment]
From this experiment we want to see how real people use this feature without creating a huge support overhead or exposing the majority of users to this MVP. So we're only going to enable it for a few councils.

It would be good to do some councils in different locations so that we can get a more diverse set of users and councillors.

I think we start with two councils, it seems like the minimum number to achieve what we want.

I think Marrickville Council is a good one because:

* It’s got a pretty diverse population by age, ethnicity and income
* it’s close by so we can go and see people and do testing in person if we want
* It's got a pretty diverse council politically
* we already have the councillor data we need
* there are a lot of active PlanningAlerts users in the area, so we're likely to see the feature used.

Not sure for the second council. I think it would be good to have something a bit different. Not an inner-city council, for example.

**Comment by henare** [comment]
Here's data on how many comments have ever been made, by authority (plus more) https://docs.google.com/spreadsheets/d/1WBNBTUNdQU22_62vkHNtX8GRJbA0E0joa8S-QpPbTPE/edit#gid=1304015817

**Comment by henare** [comment]
[Toowoomba Regional Council](https://en.wikipedia.org/wiki/Toowoomba_Region) has the next highest number of comments for a council that is not in a metro area. It could be a good choice.

Its political make up is also very different to Marrickville. In Toowoomba all councillors are either LNP or independent, [in Marrickville](https://en.wikipedia.org/wiki/Marrickville_Council#Current_composition_and_election_method) it's 4 Green, 4 ALP, 2 Liberal, 2 independent.

**Comment by henare** [comment]
There's not a lot of [recent comments in Toowoomba](https://www.planningalerts.org.au/authorities/toowoomba/comments) so I think we should do one more too.

How about the next busiest but in a different state? That would be [Boroondara City Council](https://en.wikipedia.org/wiki/City_of_Boroondara#Current_composition_and_election_method) in Victoria. It's got an interesting elected make up too - almost all independent (8) with 1 ALP and 1 Liberal.

**Comment by equivalentideas** [comment]
> How about the next busiest but in a different state? That would be Boroondara City Council in Victoria. It's got an interesting elected make up too - almost all independent (8) with 1 ALP and 1 Liberal.

That sounds good to me, thanks for picking this up :tropical_drink:

**Comment by henare** [comment]
I've got an idea - how about we do a staged rollout to these councils too. Let's just do Marrickville today and then the other two over the next few days. That way if there's any major problems we've got time to fix them.

**Comment by henare** [comment]
I've collected all the things: https://docs.google.com/spreadsheets/d/10K_75DuhGbTp7aPdzg7UlDd3siKjQhK0LoItdxA5Fbo/edit#gid=149933212

**Comment by equivalentideas** [comment]
Toowoomba Regional Council, Boroondara City Council and Marrickville Council are all now live with the councillors added.

The images for Toowoomba and Boroondara aren't available with https from the councils site, so I put them in the internet archive here https://archive.org/download/australian_local_councillor_images

**Comment by henare** [comment]
>The images for Toowoomba and Boroondara aren't available with https from the councils site, so I put them in the internet archive here https://archive.org/download/australian_local_councillor_images

That is very awesome :sparkles:
