### ISSUE TITLE
allow people to contact more than one councillor

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#861]
Lots of reasons why you may want to contact more than one councillor.
- you don't know any of them, or who might respond
- you know several of them
- you want to contact all councillors  in one ward (if there is one)
- you want to contact everyone who you know is interested in a particular issue
- you want to contact all the councillors with a particular political broad leaning or party

**Comment by henare** [comment]
I've been thinking about contacting my councillors to ask about a specific type of development that's happening in my area. I'm not sure if I'm for or against this development and so I want to ask councillors what they think of it and if council had thought about it or had any policies on it.

In this case I definitely want to email _all_ my councillors, not just one as we currently allow. This is because I want to know all of their positions on this issue. It will also be interesting to see who responds and who doesn't, and if there are groups of councillors that have different positions.

This has made me realise that even though I know some of the individuals on council, that doesn't really matter to me when I'm contacting them about development. The individual isn't important, it's the position they hold, i.e. being a councillor, that matters and so I want to email all of those people.
