### ISSUE TITLE
Handle councillors with no email

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#898]
We're probably going to start with a whole bunch of councillors we don't have email addresses for (#896) so we need to nicely handle that. Do we show the write to councillor thing if they have no email? Do we ask people to find the information for us and contribute it?

**Comment by equivalentideas** [comment]
## Do we show the write to councillor thing if they have no email?

There are four states that an application’s authority might have with this:

1. **No councillors** for the authority
2. We **have councillors** but **none of their emails**
3. We **have councillors** and **some of their emails**
4. We **have councillors** and **all of their emails**

Once we [import our scraped councillor data](https://github.com/openaustralia/planningalerts/issues/897), we'll have lots of authorities in buckets 1 and 2. **I don't think we'll have many councils in bucket 3 much of the time because, in my experience, it would be a very odd situation to collect some of the councillors emails but not all**. All our councils with councillors are currently in bucket 4, this is the situation we have a working design for.

I think that we shouldn't enable writing to councillors if we're missing emails for any councillors, because I suspect it will be a corner case. In other words, only show writing to councillors if an application’s authority is in bucket 4. If we see that bucket 3 is a common situation we might reassess.

What do you think of that @henare ?

## Do we ask people to find the information for us and contribute it?

I've just created a new issue to work out how we get people to contribute councillor information https://github.com/openaustralia/planningalerts/issues/911. I think we should make this issue about the first question and use the discussion on the new issue to work out the best ways to get people to contribute.

**Comment by equivalentideas** [comment]
Just had a chat with @henare about this.

Here’s what we came up with:

* We'll roll this out slowly and assume they'll be some admin overhead at the start
* We wont show the WriteToCouncillors stuff unless we have full data for all Councillors on the authority
* The simple way to do this is to manually toggle the feature on and off for an authority in the admin

So we need to add that feature toggler control. I'll create a new issue for that and close this issue.

**Comment by equivalentideas** [comment]
Since we've now worked this out, I'll close this issue and make the change specified in #914.
