### ISSUE TITLE
Can't find emails to councillors in Cuttlefish 

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#910]
We definitely know some have been delivered so why aren't they in Cuttlefish?

**Comment by henare** [comment]
I think it's because they go via WriteIt. We can't see these because we're not part of the WriteIt team on Cuttlefish.

**Comment by equivalentideas** [comment]
A note on this, I have a memory of doing some support where a councillor wasn't receiving emails from WriteIt. If I remember correctly it was because they were blacklisted, and I couldn't find it in Cuttlefish. I ended up tracking it down and removing the blacklisting on the rails console for cuttlefish to bypass the team access. Not a great process :S
