### ISSUE TITLE
When people follow link for alert, don't show 'sign up for an alert'

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#983]
because they already have one!

**Comment by mlandauer** [comment]
It would be problematic to have a special url for applications from alerts which doesn't show the sign up box on it. This is because the person might share the URL with a friend and you definitely want them to see the sign up box!

So, I think a better solution would be to wait until we have user login/registration. Then, if you're sign in it knows what alerts you have and if it's showing you an application that is already within your alert radius then it doesn't show the sign up box
