### ISSUE TITLE
when I receive a alert email, if I'm asked a question about an interesting application, I might be more likely to respond

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#992]
at the moment it says "add your own comment" - this is a missed opportunity to bring a question about the sense of responsibility of the community member. It could also be a point at which we remind people to say something respectfully and responsibly. 

![screen shot 2016-06-24 at 11 04 07 am](https://cloud.githubusercontent.com/assets/1239550/16324820/6b75d5f4-39fb-11e6-98a9-4cc94d594955.png)

**Comment by equivalentideas** [comment]
I think a first step to this is adding that question to frame the interaction. “Should this go ahead?” reframes the planning feedback process to put the citizen in the position of responsibility for how their area changes.

It also encourages positive contributions as well: “I think this should go ahead because ... ”. I think this is good because it makes participating in local planning less defensive—you can also see that there are possibilities to improve things as well as stop negative changes.

![screen shot 2016-06-24 at 10 59 08 am](https://cloud.githubusercontent.com/assets/1239550/16324756/ba67dc1c-39fa-11e6-9267-75905023e783.png)

I think we could do more with the link text though too. For starters it's not very consistent with how we talk about this action on the site:

* “Have your say on this application”
* “Post your public comment”
* “Have your say by adding your own comment”

![screen shot 2016-06-24 at 11 10 35 am](https://cloud.githubusercontent.com/assets/1239550/16324922/51353882-39fc-11e6-92ce-9659799ca899.png)

![screen shot 2016-06-24 at 11 10 17 am](https://cloud.githubusercontent.com/assets/1239550/16324923/534794d0-39fc-11e6-9791-f03d665795c9.png)

Also as @kat says above:

> this is a missed opportunity to bring a question about the sense of responsibility of the community member. It could also be a point at which we remind people to say something respectfully and responsibly.

**Comment by equivalentideas** [comment]
I like the word “Add” because it's a simple form of “contribute”.

Right now I can think of a small change. Replacing the word “own” with “public”. This emphasises that this is for everyone to see, and that the user is part of a community who also have a say.

![screen shot 2016-06-24 at 12 13 21 pm](https://cloud.githubusercontent.com/assets/1239550/16325856/349b9ac8-3a05-11e6-8fe1-cdca48b7cfe6.png)

Compared to current:
![screen shot 2016-06-24 at 12 17 41 pm](https://cloud.githubusercontent.com/assets/1239550/16325927/aedb0468-3a05-11e6-9ab1-7e08b6a38fbc.png)

**Comment by equivalentideas** [comment]
After looking at this with @henare we thought that this isn't the right moment for a change like this because we've made a lot of other changes and it will be hard to detect the impact of a subtle change like this. I'm going to leave this hear and give it some fresh eyes in a while. Any other thoughts or ideas welcome :)
